--
-- PostgreSQL database dump
--

\restrict 0ksh5doN4SpdSLwwDICMrCj9Fi8MR2wMLSBvFhMmFQ3jqPMMbGEr7L5rjvfGqfh

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

-- Started on 2026-05-18 14:17:24

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE IF EXISTS garagehub;
--
-- TOC entry 5210 (class 1262 OID 74332)
-- Name: garagehub; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE garagehub WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'English_United States.1252';


ALTER DATABASE garagehub OWNER TO postgres;

\unrestrict 0ksh5doN4SpdSLwwDICMrCj9Fi8MR2wMLSBvFhMmFQ3jqPMMbGEr7L5rjvfGqfh
\connect garagehub
\restrict 0ksh5doN4SpdSLwwDICMrCj9Fi8MR2wMLSBvFhMmFQ3jqPMMbGEr7L5rjvfGqfh

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 5211 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 250 (class 1259 OID 74647)
-- Name: Appointments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Appointments" (
    "AppointmentId" integer NOT NULL,
    "CustomerId" integer NOT NULL,
    "VehicleId" integer NOT NULL,
    "StaffId" integer,
    "ScheduledAt" timestamp with time zone NOT NULL,
    "ServiceType" text NOT NULL,
    "Status" text NOT NULL,
    "Notes" text
);


ALTER TABLE public."Appointments" OWNER TO postgres;

--
-- TOC entry 249 (class 1259 OID 74646)
-- Name: Appointments_AppointmentId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Appointments" ALTER COLUMN "AppointmentId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Appointments_AppointmentId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 74475)
-- Name: AspNetRoleClaims; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetRoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" integer NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetRoleClaims" OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 74474)
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetRoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 74450)
-- Name: AspNetRoles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetRoles" (
    "Id" integer NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);


ALTER TABLE public."AspNetRoles" OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 74449)
-- Name: AspNetRoles_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetRoles" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoles_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 74490)
-- Name: AspNetUserClaims; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserClaims" (
    "Id" integer NOT NULL,
    "UserId" integer NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetUserClaims" OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 74489)
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetUserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 74504)
-- Name: AspNetUserLogins; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" integer NOT NULL
);


ALTER TABLE public."AspNetUserLogins" OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 74519)
-- Name: AspNetUserRoles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserRoles" (
    "UserId" integer NOT NULL,
    "RoleId" integer NOT NULL
);


ALTER TABLE public."AspNetUserRoles" OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 74536)
-- Name: AspNetUserTokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserTokens" (
    "UserId" integer NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text
);


ALTER TABLE public."AspNetUserTokens" OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 74459)
-- Name: AspNetUsers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUsers" (
    "Id" integer NOT NULL,
    "Phone" character varying(20) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    "FirstName" character varying(100) DEFAULT ''::text NOT NULL,
    "LastName" character varying(100) DEFAULT ''::text NOT NULL
);


ALTER TABLE public."AspNetUsers" OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 74458)
-- Name: AspNetUsers_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetUsers" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUsers_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 74369)
-- Name: Invoices; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Invoices" (
    "Id" integer NOT NULL,
    "SaleId" integer NOT NULL,
    "InvoiceNumber" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "Status" text NOT NULL
);


ALTER TABLE public."Invoices" OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 74368)
-- Name: Invoices_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Invoices" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Invoices_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 74552)
-- Name: Notifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Notifications" (
    "NotificationId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "Type" text NOT NULL,
    "Message" text NOT NULL,
    "IsRead" boolean NOT NULL,
    "SentAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Notifications" OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 74551)
-- Name: Notifications_NotificationId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Notifications" ALTER COLUMN "NotificationId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Notifications_NotificationId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 242 (class 1259 OID 74571)
-- Name: PartRequests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PartRequests" (
    "RequestId" integer NOT NULL,
    "CustomerId" integer NOT NULL,
    "PartName" text NOT NULL,
    "Description" text NOT NULL,
    "Status" text NOT NULL,
    "RequestedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."PartRequests" OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 74570)
-- Name: PartRequests_RequestId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."PartRequests" ALTER COLUMN "RequestId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PartRequests_RequestId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 74341)
-- Name: Parts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Parts" (
    "Id" integer NOT NULL,
    "PartName" text NOT NULL,
    "Brand" text NOT NULL,
    "Price" numeric NOT NULL,
    "StockQuantity" integer NOT NULL,
    "VendorId" integer,
    "CreatedAt" timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL,
    "Description" text DEFAULT ''::text NOT NULL
);


ALTER TABLE public."Parts" OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 74340)
-- Name: Parts_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Parts" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Parts_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 252 (class 1259 OID 74671)
-- Name: Reviews; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Reviews" (
    "ReviewId" integer NOT NULL,
    "CustomerId" integer NOT NULL,
    "AppointmentId" integer NOT NULL,
    "Rating" integer NOT NULL,
    "Comment" text,
    "ReviewedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Reviews" OWNER TO postgres;

--
-- TOC entry 251 (class 1259 OID 74670)
-- Name: Reviews_ReviewId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Reviews" ALTER COLUMN "ReviewId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Reviews_ReviewId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 74387)
-- Name: SaleItems; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."SaleItems" (
    "Id" integer NOT NULL,
    "SaleId" integer NOT NULL,
    "PartId" integer NOT NULL,
    "Quantity" integer NOT NULL,
    "UnitPrice" numeric NOT NULL,
    "TotalPrice" numeric NOT NULL
);


ALTER TABLE public."SaleItems" OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 74386)
-- Name: SaleItems_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."SaleItems" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."SaleItems_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 74354)
-- Name: Sales; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Sales" (
    "Id" integer NOT NULL,
    "CustomerId" integer NOT NULL,
    "SubTotal" numeric NOT NULL,
    "TaxAmount" numeric NOT NULL,
    "GrandTotal" numeric NOT NULL,
    "SaleDate" timestamp with time zone NOT NULL,
    "PaymentMethod" text NOT NULL
);


ALTER TABLE public."Sales" OWNER TO postgres;

--
-- TOC entry 248 (class 1259 OID 74631)
-- Name: SalesInvoiceItems; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."SalesInvoiceItems" (
    "ItemId" integer NOT NULL,
    "SaleId" integer NOT NULL,
    "PartId" integer NOT NULL,
    "Quantity" integer NOT NULL,
    "UnitPrice" real NOT NULL,
    "TotalPrice" real DEFAULT 0 NOT NULL
);


ALTER TABLE public."SalesInvoiceItems" OWNER TO postgres;

--
-- TOC entry 247 (class 1259 OID 74630)
-- Name: SalesInvoiceItems_ItemId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."SalesInvoiceItems" ALTER COLUMN "ItemId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."SalesInvoiceItems_ItemId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 244 (class 1259 OID 74590)
-- Name: SalesInvoices; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."SalesInvoices" (
    "SaleId" integer NOT NULL,
    "CustomerId" integer NOT NULL,
    "StaffId" integer,
    "SaleDate" timestamp with time zone NOT NULL,
    "Subtotal" real NOT NULL,
    "DiscountApplied" real NOT NULL,
    "TotalAmount" real NOT NULL,
    "PaymentStatus" text NOT NULL,
    "CreditUsed" boolean NOT NULL
);


ALTER TABLE public."SalesInvoices" OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 74589)
-- Name: SalesInvoices_SaleId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."SalesInvoices" ALTER COLUMN "SaleId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."SalesInvoices_SaleId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 74353)
-- Name: Sales_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Sales" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Sales_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 246 (class 1259 OID 74611)
-- Name: Vehicles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Vehicles" (
    "VehicleId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "VehicleNumber" text NOT NULL,
    "Make" text NOT NULL,
    "Model" text NOT NULL,
    "Year" integer NOT NULL,
    "Vin" text NOT NULL
);


ALTER TABLE public."Vehicles" OWNER TO postgres;

--
-- TOC entry 245 (class 1259 OID 74610)
-- Name: Vehicles_VehicleId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Vehicles" ALTER COLUMN "VehicleId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Vehicles_VehicleId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 74333)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 5202 (class 0 OID 74647)
-- Dependencies: 250
-- Data for Name: Appointments; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Appointments" VALUES (1, 4, 1, NULL, '2026-05-20 05:45:00+05:45', 'Oil Change', 'pending', '') ON CONFLICT DO NOTHING;


--
-- TOC entry 5185 (class 0 OID 74475)
-- Dependencies: 233
-- Data for Name: AspNetRoleClaims; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5181 (class 0 OID 74450)
-- Dependencies: 229
-- Data for Name: AspNetRoles; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."AspNetRoles" VALUES (1, 'admin', 'ADMIN', '07fbdf5c-a977-4ae2-abfd-c075a45a7cdc') ON CONFLICT DO NOTHING;
INSERT INTO public."AspNetRoles" VALUES (2, 'staff', 'STAFF', 'd5fc87a7-07dc-4b0f-806e-1431b2a638f8') ON CONFLICT DO NOTHING;
INSERT INTO public."AspNetRoles" VALUES (3, 'customer', 'CUSTOMER', 'a5bc2b3d-4c4f-41cb-8cd5-d57e664d05fe') ON CONFLICT DO NOTHING;


--
-- TOC entry 5187 (class 0 OID 74490)
-- Dependencies: 235
-- Data for Name: AspNetUserClaims; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5188 (class 0 OID 74504)
-- Dependencies: 236
-- Data for Name: AspNetUserLogins; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5189 (class 0 OID 74519)
-- Dependencies: 237
-- Data for Name: AspNetUserRoles; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."AspNetUserRoles" VALUES (1, 1) ON CONFLICT DO NOTHING;
INSERT INTO public."AspNetUserRoles" VALUES (2, 2) ON CONFLICT DO NOTHING;
INSERT INTO public."AspNetUserRoles" VALUES (3, 2) ON CONFLICT DO NOTHING;
INSERT INTO public."AspNetUserRoles" VALUES (4, 3) ON CONFLICT DO NOTHING;


--
-- TOC entry 5190 (class 0 OID 74536)
-- Dependencies: 238
-- Data for Name: AspNetUserTokens; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5183 (class 0 OID 74459)
-- Dependencies: 231
-- Data for Name: AspNetUsers; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."AspNetUsers" VALUES (1, '+1234567890', '2026-05-15 10:27:55.594926+05:45', 'smartsikchya.noreply@gmail.com', 'SMARTSIKCHYA.NOREPLY@GMAIL.COM', 'smartsikchya.noreply@gmail.com', 'SMARTSIKCHYA.NOREPLY@GMAIL.COM', true, 'AQAAAAIAAYagAAAAENMJ0FLMUdRzticRvO3bHZpgRRUW+a24Crwnsmx1I5OV13XqxhcS0OFD95Cf4Sx+ng==', 'M5MRAWNWHAOCZLGPZ4UQQKHX6UV7RJZA', '5bcb2a1c-32ca-4b63-8639-0960654cc69c', NULL, false, false, NULL, true, 0, 'Admin', 'User') ON CONFLICT DO NOTHING;
INSERT INTO public."AspNetUsers" VALUES (2, '9787875454', '2026-05-15 10:36:35.781747+05:45', 'pragunmaskeyofficial@gmail.com', 'PRAGUNMASKEYOFFICIAL@GMAIL.COM', 'pragunmaskeyofficial@gmail.com', 'PRAGUNMASKEYOFFICIAL@GMAIL.COM', true, 'AQAAAAIAAYagAAAAEAT2uwMQPmgeZSOzqyqcvSv9/ASjsup7c9KJ3oti2Q+0+JCzGdCe2T1x+x6q/BAhmw==', 'H77KDCJEUZIU6PVGBC2LCK33NZT4JCSK', '18c1921b-c95f-4dce-9272-8c40a2c3c72c', NULL, false, false, NULL, true, 0, 'Pragun', 'Maskey') ON CONFLICT DO NOTHING;
INSERT INTO public."AspNetUsers" VALUES (3, '9856874539', '2026-05-15 10:38:04.264458+05:45', 'ram123@gmail.com', 'RAM123@GMAIL.COM', 'ram123@gmail.com', 'RAM123@GMAIL.COM', true, 'AQAAAAIAAYagAAAAEA9KNRWKug+PO0hRrM8R2Bbzxv1mhtNMU1Ggalr6hneBmqPkVs1YwEi1xHKKmQDBGw==', 'UPDRC347ZROZ46XJX6NXPZLPDJRLX5WH', 'b4235b08-aa48-4492-b14b-80e247ceced1', NULL, false, false, NULL, true, 0, 'Ram', 'Kumar') ON CONFLICT DO NOTHING;
INSERT INTO public."AspNetUsers" VALUES (4, '8967872487', '2026-05-15 10:39:45.078942+05:45', 'shyam@gmail.com', 'SHYAM@GMAIL.COM', 'shyam@gmail.com', 'SHYAM@GMAIL.COM', true, 'AQAAAAIAAYagAAAAEFc1rzWrRIAFVmirfe+w6ojBVtNSoGBQqM/ZecShc4szrAVIA92tSP2hFeJTwA/Gxg==', 'PQDXVJYIIY6INHKWPHIWR7LZYVOPPMFS', '7d41425c-1707-4024-81d2-3bd41a68b972', NULL, false, false, NULL, true, 0, 'Shyam', 'Bhandari') ON CONFLICT DO NOTHING;


--
-- TOC entry 5177 (class 0 OID 74369)
-- Dependencies: 225
-- Data for Name: Invoices; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5192 (class 0 OID 74552)
-- Dependencies: 240
-- Data for Name: Notifications; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5194 (class 0 OID 74571)
-- Dependencies: 242
-- Data for Name: PartRequests; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5173 (class 0 OID 74341)
-- Dependencies: 221
-- Data for Name: Parts; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5204 (class 0 OID 74671)
-- Dependencies: 252
-- Data for Name: Reviews; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5179 (class 0 OID 74387)
-- Dependencies: 227
-- Data for Name: SaleItems; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5175 (class 0 OID 74354)
-- Dependencies: 223
-- Data for Name: Sales; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5200 (class 0 OID 74631)
-- Dependencies: 248
-- Data for Name: SalesInvoiceItems; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5196 (class 0 OID 74590)
-- Dependencies: 244
-- Data for Name: SalesInvoices; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5198 (class 0 OID 74611)
-- Dependencies: 246
-- Data for Name: Vehicles; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Vehicles" VALUES (1, 4, 'BA-2-Pa-2341', 'Toyota', 'Camry', 2026, '') ON CONFLICT DO NOTHING;


--
-- TOC entry 5171 (class 0 OID 74333)
-- Dependencies: 219
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."__EFMigrationsHistory" VALUES ('20260428200153_InitialCreate', '10.0.7') ON CONFLICT DO NOTHING;
INSERT INTO public."__EFMigrationsHistory" VALUES ('20260430084732_AddMissingEntityConfigurations', '10.0.7') ON CONFLICT DO NOTHING;
INSERT INTO public."__EFMigrationsHistory" VALUES ('20260503041929_AddFirstNameLastNameToUser', '10.0.7') ON CONFLICT DO NOTHING;
INSERT INTO public."__EFMigrationsHistory" VALUES ('20260503100553_AddMissingPartColumns', '10.0.7') ON CONFLICT DO NOTHING;
INSERT INTO public."__EFMigrationsHistory" VALUES ('20260515043823_updateSchema', '10.0.7') ON CONFLICT DO NOTHING;


--
-- TOC entry 5212 (class 0 OID 0)
-- Dependencies: 249
-- Name: Appointments_AppointmentId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Appointments_AppointmentId_seq"', 1, true);


--
-- TOC entry 5213 (class 0 OID 0)
-- Dependencies: 232
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."AspNetRoleClaims_Id_seq"', 1, false);


--
-- TOC entry 5214 (class 0 OID 0)
-- Dependencies: 228
-- Name: AspNetRoles_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."AspNetRoles_Id_seq"', 3, true);


--
-- TOC entry 5215 (class 0 OID 0)
-- Dependencies: 234
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."AspNetUserClaims_Id_seq"', 1, false);


--
-- TOC entry 5216 (class 0 OID 0)
-- Dependencies: 230
-- Name: AspNetUsers_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."AspNetUsers_Id_seq"', 4, true);


--
-- TOC entry 5217 (class 0 OID 0)
-- Dependencies: 224
-- Name: Invoices_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Invoices_Id_seq"', 1, false);


--
-- TOC entry 5218 (class 0 OID 0)
-- Dependencies: 239
-- Name: Notifications_NotificationId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Notifications_NotificationId_seq"', 1, false);


--
-- TOC entry 5219 (class 0 OID 0)
-- Dependencies: 241
-- Name: PartRequests_RequestId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."PartRequests_RequestId_seq"', 1, false);


--
-- TOC entry 5220 (class 0 OID 0)
-- Dependencies: 220
-- Name: Parts_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Parts_Id_seq"', 1, false);


--
-- TOC entry 5221 (class 0 OID 0)
-- Dependencies: 251
-- Name: Reviews_ReviewId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Reviews_ReviewId_seq"', 1, false);


--
-- TOC entry 5222 (class 0 OID 0)
-- Dependencies: 226
-- Name: SaleItems_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."SaleItems_Id_seq"', 1, false);


--
-- TOC entry 5223 (class 0 OID 0)
-- Dependencies: 247
-- Name: SalesInvoiceItems_ItemId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."SalesInvoiceItems_ItemId_seq"', 1, false);


--
-- TOC entry 5224 (class 0 OID 0)
-- Dependencies: 243
-- Name: SalesInvoices_SaleId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."SalesInvoices_SaleId_seq"', 1, false);


--
-- TOC entry 5225 (class 0 OID 0)
-- Dependencies: 222
-- Name: Sales_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Sales_Id_seq"', 1, false);


--
-- TOC entry 5226 (class 0 OID 0)
-- Dependencies: 245
-- Name: Vehicles_VehicleId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Vehicles_VehicleId_seq"', 1, true);


--
-- TOC entry 5000 (class 2606 OID 74659)
-- Name: Appointments PK_Appointments; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Appointments"
    ADD CONSTRAINT "PK_Appointments" PRIMARY KEY ("AppointmentId");


--
-- TOC entry 4970 (class 2606 OID 74483)
-- Name: AspNetRoleClaims PK_AspNetRoleClaims; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");


--
-- TOC entry 4962 (class 2606 OID 74457)
-- Name: AspNetRoles PK_AspNetRoles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoles"
    ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");


--
-- TOC entry 4973 (class 2606 OID 74498)
-- Name: AspNetUserClaims PK_AspNetUserClaims; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");


--
-- TOC entry 4976 (class 2606 OID 74513)
-- Name: AspNetUserLogins PK_AspNetUserLogins; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- TOC entry 4979 (class 2606 OID 74525)
-- Name: AspNetUserRoles PK_AspNetUserRoles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");


--
-- TOC entry 4981 (class 2606 OID 74545)
-- Name: AspNetUserTokens PK_AspNetUserTokens; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- TOC entry 4966 (class 2606 OID 74473)
-- Name: AspNetUsers PK_AspNetUsers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUsers"
    ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");


--
-- TOC entry 4956 (class 2606 OID 74380)
-- Name: Invoices PK_Invoices; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Invoices"
    ADD CONSTRAINT "PK_Invoices" PRIMARY KEY ("Id");


--
-- TOC entry 4984 (class 2606 OID 74564)
-- Name: Notifications PK_Notifications; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Notifications"
    ADD CONSTRAINT "PK_Notifications" PRIMARY KEY ("NotificationId");


--
-- TOC entry 4987 (class 2606 OID 74583)
-- Name: PartRequests PK_PartRequests; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PartRequests"
    ADD CONSTRAINT "PK_PartRequests" PRIMARY KEY ("RequestId");


--
-- TOC entry 4950 (class 2606 OID 74352)
-- Name: Parts PK_Parts; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Parts"
    ADD CONSTRAINT "PK_Parts" PRIMARY KEY ("Id");


--
-- TOC entry 5004 (class 2606 OID 74682)
-- Name: Reviews PK_Reviews; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Reviews"
    ADD CONSTRAINT "PK_Reviews" PRIMARY KEY ("ReviewId");


--
-- TOC entry 4960 (class 2606 OID 74399)
-- Name: SaleItems PK_SaleItems; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SaleItems"
    ADD CONSTRAINT "PK_SaleItems" PRIMARY KEY ("Id");


--
-- TOC entry 4953 (class 2606 OID 74367)
-- Name: Sales PK_Sales; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Sales"
    ADD CONSTRAINT "PK_Sales" PRIMARY KEY ("Id");


--
-- TOC entry 4996 (class 2606 OID 74640)
-- Name: SalesInvoiceItems PK_SalesInvoiceItems; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SalesInvoiceItems"
    ADD CONSTRAINT "PK_SalesInvoiceItems" PRIMARY KEY ("ItemId");


--
-- TOC entry 4990 (class 2606 OID 74604)
-- Name: SalesInvoices PK_SalesInvoices; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SalesInvoices"
    ADD CONSTRAINT "PK_SalesInvoices" PRIMARY KEY ("SaleId");


--
-- TOC entry 4993 (class 2606 OID 74624)
-- Name: Vehicles PK_Vehicles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Vehicles"
    ADD CONSTRAINT "PK_Vehicles" PRIMARY KEY ("VehicleId");


--
-- TOC entry 4948 (class 2606 OID 74339)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 4964 (class 1259 OID 74702)
-- Name: EmailIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "EmailIndex" ON public."AspNetUsers" USING btree ("NormalizedEmail");


--
-- TOC entry 4997 (class 1259 OID 74695)
-- Name: IX_Appointments_CustomerId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Appointments_CustomerId" ON public."Appointments" USING btree ("CustomerId");


--
-- TOC entry 4998 (class 1259 OID 74696)
-- Name: IX_Appointments_VehicleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Appointments_VehicleId" ON public."Appointments" USING btree ("VehicleId");


--
-- TOC entry 4968 (class 1259 OID 74697)
-- Name: IX_AspNetRoleClaims_RoleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON public."AspNetRoleClaims" USING btree ("RoleId");


--
-- TOC entry 4971 (class 1259 OID 74699)
-- Name: IX_AspNetUserClaims_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserClaims_UserId" ON public."AspNetUserClaims" USING btree ("UserId");


--
-- TOC entry 4974 (class 1259 OID 74700)
-- Name: IX_AspNetUserLogins_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserLogins_UserId" ON public."AspNetUserLogins" USING btree ("UserId");


--
-- TOC entry 4977 (class 1259 OID 74701)
-- Name: IX_AspNetUserRoles_RoleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON public."AspNetUserRoles" USING btree ("RoleId");


--
-- TOC entry 4954 (class 1259 OID 74405)
-- Name: IX_Invoices_SaleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Invoices_SaleId" ON public."Invoices" USING btree ("SaleId");


--
-- TOC entry 4982 (class 1259 OID 74704)
-- Name: IX_Notifications_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Notifications_UserId" ON public."Notifications" USING btree ("UserId");


--
-- TOC entry 4985 (class 1259 OID 74705)
-- Name: IX_PartRequests_CustomerId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PartRequests_CustomerId" ON public."PartRequests" USING btree ("CustomerId");


--
-- TOC entry 5001 (class 1259 OID 74706)
-- Name: IX_Reviews_AppointmentId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Reviews_AppointmentId" ON public."Reviews" USING btree ("AppointmentId");


--
-- TOC entry 5002 (class 1259 OID 74707)
-- Name: IX_Reviews_CustomerId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Reviews_CustomerId" ON public."Reviews" USING btree ("CustomerId");


--
-- TOC entry 4957 (class 1259 OID 74694)
-- Name: IX_SaleItems_PartId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_SaleItems_PartId" ON public."SaleItems" USING btree ("PartId");


--
-- TOC entry 4958 (class 1259 OID 74406)
-- Name: IX_SaleItems_SaleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_SaleItems_SaleId" ON public."SaleItems" USING btree ("SaleId");


--
-- TOC entry 4994 (class 1259 OID 74708)
-- Name: IX_SalesInvoiceItems_SaleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_SalesInvoiceItems_SaleId" ON public."SalesInvoiceItems" USING btree ("SaleId");


--
-- TOC entry 4988 (class 1259 OID 74709)
-- Name: IX_SalesInvoices_CustomerId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_SalesInvoices_CustomerId" ON public."SalesInvoices" USING btree ("CustomerId");


--
-- TOC entry 4951 (class 1259 OID 74693)
-- Name: IX_Sales_CustomerId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Sales_CustomerId" ON public."Sales" USING btree ("CustomerId");


--
-- TOC entry 4991 (class 1259 OID 74710)
-- Name: IX_Vehicles_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Vehicles_UserId" ON public."Vehicles" USING btree ("UserId");


--
-- TOC entry 4963 (class 1259 OID 74698)
-- Name: RoleNameIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "RoleNameIndex" ON public."AspNetRoles" USING btree ("NormalizedName");


--
-- TOC entry 4967 (class 1259 OID 74703)
-- Name: UserNameIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "UserNameIndex" ON public."AspNetUsers" USING btree ("NormalizedUserName");


--
-- TOC entry 5020 (class 2606 OID 74660)
-- Name: Appointments FK_Appointments_AspNetUsers_CustomerId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Appointments"
    ADD CONSTRAINT "FK_Appointments_AspNetUsers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT;


--
-- TOC entry 5021 (class 2606 OID 74665)
-- Name: Appointments FK_Appointments_Vehicles_VehicleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Appointments"
    ADD CONSTRAINT "FK_Appointments_Vehicles_VehicleId" FOREIGN KEY ("VehicleId") REFERENCES public."Vehicles"("VehicleId") ON DELETE RESTRICT;


--
-- TOC entry 5009 (class 2606 OID 74484)
-- Name: AspNetRoleClaims FK_AspNetRoleClaims_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- TOC entry 5010 (class 2606 OID 74499)
-- Name: AspNetUserClaims FK_AspNetUserClaims_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 5011 (class 2606 OID 74514)
-- Name: AspNetUserLogins FK_AspNetUserLogins_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 5012 (class 2606 OID 74526)
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- TOC entry 5013 (class 2606 OID 74531)
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 5014 (class 2606 OID 74546)
-- Name: AspNetUserTokens FK_AspNetUserTokens_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 5006 (class 2606 OID 74381)
-- Name: Invoices FK_Invoices_Sales_SaleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Invoices"
    ADD CONSTRAINT "FK_Invoices_Sales_SaleId" FOREIGN KEY ("SaleId") REFERENCES public."Sales"("Id") ON DELETE CASCADE;


--
-- TOC entry 5015 (class 2606 OID 74565)
-- Name: Notifications FK_Notifications_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Notifications"
    ADD CONSTRAINT "FK_Notifications_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 5016 (class 2606 OID 74584)
-- Name: PartRequests FK_PartRequests_AspNetUsers_CustomerId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PartRequests"
    ADD CONSTRAINT "FK_PartRequests_AspNetUsers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 5022 (class 2606 OID 74683)
-- Name: Reviews FK_Reviews_Appointments_AppointmentId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Reviews"
    ADD CONSTRAINT "FK_Reviews_Appointments_AppointmentId" FOREIGN KEY ("AppointmentId") REFERENCES public."Appointments"("AppointmentId") ON DELETE RESTRICT;


--
-- TOC entry 5023 (class 2606 OID 74688)
-- Name: Reviews FK_Reviews_AspNetUsers_CustomerId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Reviews"
    ADD CONSTRAINT "FK_Reviews_AspNetUsers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT;


--
-- TOC entry 5007 (class 2606 OID 74711)
-- Name: SaleItems FK_SaleItems_Parts_PartId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SaleItems"
    ADD CONSTRAINT "FK_SaleItems_Parts_PartId" FOREIGN KEY ("PartId") REFERENCES public."Parts"("Id") ON DELETE RESTRICT;


--
-- TOC entry 5008 (class 2606 OID 74400)
-- Name: SaleItems FK_SaleItems_Sales_SaleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SaleItems"
    ADD CONSTRAINT "FK_SaleItems_Sales_SaleId" FOREIGN KEY ("SaleId") REFERENCES public."Sales"("Id") ON DELETE CASCADE;


--
-- TOC entry 5019 (class 2606 OID 74641)
-- Name: SalesInvoiceItems FK_SalesInvoiceItems_SalesInvoices_SaleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SalesInvoiceItems"
    ADD CONSTRAINT "FK_SalesInvoiceItems_SalesInvoices_SaleId" FOREIGN KEY ("SaleId") REFERENCES public."SalesInvoices"("SaleId") ON DELETE CASCADE;


--
-- TOC entry 5017 (class 2606 OID 74605)
-- Name: SalesInvoices FK_SalesInvoices_AspNetUsers_CustomerId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SalesInvoices"
    ADD CONSTRAINT "FK_SalesInvoices_AspNetUsers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT;


--
-- TOC entry 5005 (class 2606 OID 74716)
-- Name: Sales FK_Sales_AspNetUsers_CustomerId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Sales"
    ADD CONSTRAINT "FK_Sales_AspNetUsers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT;


--
-- TOC entry 5018 (class 2606 OID 74625)
-- Name: Vehicles FK_Vehicles_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Vehicles"
    ADD CONSTRAINT "FK_Vehicles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


-- Completed on 2026-05-18 14:17:24

--
-- PostgreSQL database dump complete
--

\unrestrict 0ksh5doN4SpdSLwwDICMrCj9Fi8MR2wMLSBvFhMmFQ3jqPMMbGEr7L5rjvfGqfh

